name: tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./
          run: npm test      